stages:
  - release

release:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: [ '' ]
  only:
    - master
  variables:
    GIT_DEPTH: 0
    GITLAB_TOKEN: "FRzyPx24uWfh9GwMnKW5"
  script:
    - goreleaser release --snapshot --rm-dist